//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionStat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adresa
    {
        public int id { get; set; }
        public Nullable<short> uik { get; set; }
        public string lon { get; set; }
        public string lat { get; set; }
        public string adres { get; set; }
    }
}
