//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionStat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class uikadresaEntities : DbContext
    {
        public uikadresaEntities()
            : base("name=uikadresaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adresa> adresa { get; set; }
        public virtual DbSet<guber_2017> guber_2017 { get; set; }
        public virtual DbSet<obl_uiks_18032018> obl_uiks_18032018 { get; set; }
        public virtual DbSet<uiks> uiks { get; set; }
        public virtual DbSet<VN_18032018> VN_18032018 { get; set; }
    
        [DbFunction("uikadresaEntities", "RezOblPrez2018")]
        public virtual IQueryable<RezOblPrez2018_Result> RezOblPrez2018()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<RezOblPrez2018_Result>("[uikadresaEntities].[RezOblPrez2018]()");
        }
    }
}
