//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionStat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VN_18032018
    {
        public int id { get; set; }
        public string rayon { get; set; }
        public Nullable<short> uik { get; set; }
        public Nullable<short> p1 { get; set; }
        public Nullable<short> p2 { get; set; }
        public Nullable<short> p3 { get; set; }
        public Nullable<short> p4 { get; set; }
        public Nullable<short> p5 { get; set; }
        public Nullable<short> p6 { get; set; }
        public Nullable<short> p7 { get; set; }
        public Nullable<short> p8 { get; set; }
        public Nullable<short> p9 { get; set; }
        public Nullable<short> p10 { get; set; }
        public Nullable<short> p11 { get; set; }
        public Nullable<short> p12 { get; set; }
        public Nullable<short> k1_c { get; set; }
        public Nullable<float> k1_p { get; set; }
        public Nullable<short> k2_c { get; set; }
        public Nullable<float> k2_p { get; set; }
        public Nullable<short> k3_c { get; set; }
        public Nullable<float> k3_p { get; set; }
        public Nullable<short> k4_c { get; set; }
        public Nullable<float> k4_p { get; set; }
        public Nullable<short> k5_c { get; set; }
        public Nullable<float> k5_p { get; set; }
        public Nullable<short> k6_c { get; set; }
        public Nullable<float> k6_p { get; set; }
        public Nullable<short> k7_c { get; set; }
        public Nullable<float> k7_p { get; set; }
        public Nullable<short> k8_c { get; set; }
        public Nullable<float> k8_p { get; set; }
        public Nullable<short> voter { get; set; }
        public string adres { get; set; }
        public string lon { get; set; }
        public string lat { get; set; }
    }
}
